import { TOOL_PHRASES, fillToolPhrase, type ToolPhraseKind, type ToolPhrasePhase } from './chatToolPhrases.base'
import { createGeneratedSubtypePhrases, EXTRA_EXEC_PHRASES } from './chatToolPhrases.generated'

export { TOOL_PHRASES, fillToolPhrase, type ToolPhraseKind, type ToolPhrasePhase }

const EXPLICIT_SUBTYPE_PHRASES: Record<string, Record<ToolPhrasePhase, string[]>> = {
  read_frontend: {
    start: [
      'Ich schaue gerade in die Oberfläche rein.',
      'Ich lese gerade die UI-Stelle an.',
      'Ich prüfe gerade die Ansicht.',
      'Ich gehe gerade in den Frontend-Teil rein.',
      'Ich schaue gerade auf die sichtbare Stelle.',
    ],
    steady: [
      'Ich lese die Oberfläche gerade weiter.',
      'Ich prüfe die Ansicht gerade noch.',
      'Ich bin noch im Frontend dran.',
      'Ich gleiche die UI-Stelle gerade ab.',
      'Ich schaue mir die Oberfläche gerade weiter an.',
    ],
    deep: [
      'Ich gehe die Oberfläche noch gründlicher durch.',
      'Ich prüfe die Ansicht noch genauer.',
      'Ich bleibe noch kurz im Frontend.',
      'Ich gleiche die UI-Logik noch sauber ab.',
      'Ich lese die sichtbare Stelle noch zu Ende ein.',
    ],
  },
  read_backend: {
    start: [
      'Ich schaue gerade ins Backend rein.',
      'Ich lese gerade die Serverlogik an.',
      'Ich prüfe gerade den Hintergrundteil.',
      'Ich gehe gerade in die Backend-Stelle rein.',
      'Ich schaue gerade auf die Serverseite.',
    ],
    steady: [
      'Ich lese das Backend gerade weiter.',
      'Ich prüfe die Serverlogik gerade noch.',
      'Ich bin noch im Hintergrundteil dran.',
      'Ich gleiche die Backend-Stelle gerade ab.',
      'Ich schaue mir die Serverseite gerade weiter an.',
    ],
    deep: [
      'Ich gehe das Backend noch gründlicher durch.',
      'Ich prüfe die Serverlogik noch genauer.',
      'Ich bleibe noch kurz im Hintergrundteil.',
      'Ich gleiche die Backend-Zusammenhänge noch sauber ab.',
      'Ich lese die Serverstelle noch tiefer ein.',
    ],
  },
  read_styles: {
    start: [
      'Ich schaue gerade auf das Styling.',
      'Ich lese gerade die Styles an.',
      'Ich prüfe gerade die Optik-Stelle.',
      'Ich gehe gerade in die Designregeln rein.',
      'Ich schaue gerade auf Farben und Abstände.',
    ],
    steady: [
      'Ich lese die Styles gerade weiter.',
      'Ich prüfe das Styling gerade noch.',
      'Ich bin noch an der Optik-Stelle dran.',
      'Ich gleiche die Designregeln gerade ab.',
      'Ich schaue mir die Styles gerade weiter an.',
    ],
    deep: [
      'Ich gehe das Styling noch gründlicher durch.',
      'Ich prüfe die Optik noch genauer.',
      'Ich bleibe noch kurz bei den Styles.',
      'Ich gleiche die Designregeln noch sauber ab.',
      'Ich lese die Style-Stelle noch tiefer ein.',
    ],
  },
  read_tests: {
    start: [
      'Ich schaue gerade in die Tests rein.',
      'Ich lese gerade die Prüfstelle an.',
      'Ich prüfe gerade die Testlogik.',
      'Ich gehe gerade die Testdatei durch.',
      'Ich schaue gerade, was schon geprüft wird.',
    ],
    steady: [
      'Ich lese die Tests gerade weiter.',
      'Ich prüfe die Testlogik gerade noch.',
      'Ich bin noch an der Prüfstelle dran.',
      'Ich gleiche die Testdatei gerade ab.',
      'Ich schaue mir die Tests gerade weiter an.',
    ],
    deep: [
      'Ich gehe die Tests noch gründlicher durch.',
      'Ich prüfe die Prüflogik noch genauer.',
      'Ich bleibe noch kurz bei den Tests.',
      'Ich gleiche die Testfälle noch sauber ab.',
      'Ich lese die Teststelle noch tiefer ein.',
    ],
  },
  read_code: {
    start: [
      'Ich lese gerade den Code an.',
      'Ich schaue gerade in die Logik rein.',
      'Ich prüfe gerade den Codepfad.',
      'Ich lese die Stelle gerade kurz ein.',
      'Ich gehe gerade in den Code rein.',
    ],
    steady: [
      'Ich lese den Code gerade weiter.',
      'Ich prüfe gerade noch die Logik.',
      'Ich gleiche die Codestelle gerade ab.',
      'Ich bin noch im Code dran.',
      'Ich ordne den Code gerade noch ein.',
    ],
    deep: [
      'Ich gehe den Code noch gründlicher durch.',
      'Ich prüfe die Logik noch eine Ecke tiefer.',
      'Ich lese den Code noch sauber zu Ende.',
      'Ich gleiche die Zusammenhänge im Code noch ab.',
      'Ich bleibe noch kurz im Code, bis es klar ist.',
    ],
  },
  read_docs: {
    start: [
      'Ich lese gerade die Notizen an.',
      'Ich schaue gerade in die Doku rein.',
      'Ich prüfe gerade den Text.',
      'Ich lese gerade die Anleitung an.',
      'Ich gehe gerade die Notizen durch.',
    ],
    steady: [
      'Ich lese die Doku gerade weiter.',
      'Ich prüfe die Notizen gerade noch.',
      'Ich gehe den Text gerade weiter durch.',
      'Ich bin noch in der Anleitung dran.',
      'Ich gleiche die Notizen gerade ab.',
    ],
    deep: [
      'Ich lese die Doku noch gründlicher.',
      'Ich prüfe die Notizen noch genauer.',
      'Ich gehe den Text noch sauber zu Ende durch.',
      'Ich bleibe noch kurz in der Anleitung.',
      'Ich gleiche die Doku noch tiefer ab.',
    ],
  },
  read_settings: {
    start: [
      'Ich schaue gerade in die Einstellungen rein.',
      'Ich prüfe gerade die Konfiguration.',
      'Ich lese gerade die Config an.',
      'Ich gehe gerade die Einstellungen durch.',
      'Ich schaue gerade auf die Setup-Datei.',
    ],
    steady: [
      'Ich prüfe die Einstellungen gerade weiter.',
      'Ich lese die Config gerade noch.',
      'Ich gleiche die Konfiguration gerade ab.',
      'Ich bin noch in den Einstellungen dran.',
      'Ich prüfe die Setup-Datei gerade noch.',
    ],
    deep: [
      'Ich prüfe die Konfiguration noch gründlicher.',
      'Ich gehe die Einstellungen noch sauber durch.',
      'Ich bleibe noch kurz in der Config.',
      'Ich gleiche die Setup-Logik noch ab.',
      'Ich prüfe die Einstellungen noch bis ins Detail.',
    ],
  },
  edit_ui: {
    start: [
      'Ich passe gerade die Oberfläche an.',
      'Ich schraube gerade am Look.',
      'Ich ändere gerade die Ansicht.',
      'Ich ziehe gerade das UI gerade.',
      'Ich richte gerade die Oberfläche aus.',
    ],
    steady: [
      'Ich arbeite gerade noch an der Oberfläche.',
      'Ich gleiche die Ansicht gerade noch ab.',
      'Ich poliere das UI gerade weiter.',
      'Ich bin noch am Look dran.',
      'Ich richte die Oberfläche gerade weiter aus.',
    ],
    deep: [
      'Ich feile noch an der Oberfläche.',
      'Ich bringe das UI noch sauber in Form.',
      'Ich gleiche den Look noch genauer ab.',
      'Ich bleibe noch kurz an der Ansicht dran.',
      'Ich richte die Oberfläche noch präziser aus.',
    ],
  },
  edit_frontend: {
    start: [
      'Ich passe gerade die Oberfläche an.',
      'Ich ändere gerade die UI-Stelle.',
      'Ich richte gerade die Ansicht aus.',
      'Ich schraube gerade am Frontend.',
      'Ich ziehe gerade die sichtbare Stelle gerade.',
    ],
    steady: [
      'Ich arbeite gerade noch an der Oberfläche.',
      'Ich gleiche die UI-Stelle gerade weiter ab.',
      'Ich bin noch an der Ansicht dran.',
      'Ich richte das Frontend gerade noch aus.',
      'Ich poliere die Oberfläche gerade weiter.',
    ],
    deep: [
      'Ich feile noch an der Oberfläche.',
      'Ich bringe die Ansicht noch sauber in Form.',
      'Ich gleiche die UI noch genauer ab.',
      'Ich bleibe noch kurz am Frontend dran.',
      'Ich mache die Oberfläche gerade noch ruhiger.',
    ],
  },
  edit_backend: {
    start: [
      'Ich passe gerade das Backend an.',
      'Ich ändere gerade die Serverlogik.',
      'Ich richte gerade den Hintergrundteil aus.',
      'Ich schraube gerade an der Backend-Stelle.',
      'Ich ziehe gerade die Serverseite gerade.',
    ],
    steady: [
      'Ich arbeite gerade noch am Backend.',
      'Ich gleiche die Serverlogik gerade weiter ab.',
      'Ich bin noch am Hintergrundteil dran.',
      'Ich richte die Backend-Stelle gerade noch aus.',
      'Ich poliere die Serverlogik gerade weiter.',
    ],
    deep: [
      'Ich feile noch an der Serverlogik.',
      'Ich bringe das Backend noch sauber in Form.',
      'Ich gleiche den Hintergrundteil noch genauer ab.',
      'Ich bleibe noch kurz am Backend dran.',
      'Ich mache die Serverseite gerade noch robuster.',
    ],
  },
  edit_styles: {
    start: [
      'Ich passe gerade das Styling an.',
      'Ich ändere gerade die Optik.',
      'Ich richte gerade Farben und Abstände aus.',
      'Ich schraube gerade am Look.',
      'Ich ziehe gerade die Styles gerade.',
    ],
    steady: [
      'Ich arbeite gerade noch am Styling.',
      'Ich gleiche die Optik gerade weiter ab.',
      'Ich bin noch am Look dran.',
      'Ich richte die Styles gerade noch aus.',
      'Ich poliere das Styling gerade weiter.',
    ],
    deep: [
      'Ich feile noch an der Optik.',
      'Ich bringe das Styling noch sauber in Form.',
      'Ich gleiche die Styles noch genauer ab.',
      'Ich bleibe noch kurz am Look dran.',
      'Ich mache die Oberfläche gerade noch stimmiger.',
    ],
  },
  edit_tests: {
    start: [
      'Ich passe gerade die Tests an.',
      'Ich ändere gerade die Prüflogik.',
      'Ich richte gerade die Testfälle aus.',
      'Ich schraube gerade an den Tests.',
      'Ich ziehe gerade die Prüfstelle gerade.',
    ],
    steady: [
      'Ich arbeite gerade noch an den Tests.',
      'Ich gleiche die Prüflogik gerade weiter ab.',
      'Ich bin noch an den Testfällen dran.',
      'Ich richte die Tests gerade noch aus.',
      'Ich poliere die Prüfstelle gerade weiter.',
    ],
    deep: [
      'Ich feile noch an den Tests.',
      'Ich bringe die Prüflogik noch sauber in Form.',
      'Ich gleiche die Testfälle noch genauer ab.',
      'Ich bleibe noch kurz an den Tests dran.',
      'Ich mache die Teststelle gerade noch belastbarer.',
    ],
  },
  edit_code: {
    start: [
      'Ich ändere gerade den Code.',
      'Ich passe gerade die Logik an.',
      'Ich schraube gerade an der Funktion.',
      'Ich richte gerade die Codestelle aus.',
      'Ich ziehe gerade den Code gerade.',
    ],
    steady: [
      'Ich arbeite gerade noch am Code.',
      'Ich gleiche die Logik gerade weiter ab.',
      'Ich bin noch an der Funktion dran.',
      'Ich passe die Codestelle gerade weiter an.',
      'Ich richte die Logik gerade noch sauber aus.',
    ],
    deep: [
      'Ich feile noch an der Logik.',
      'Ich ziehe den Code noch sauber in Form.',
      'Ich gleiche die Funktion noch genauer ab.',
      'Ich bleibe noch kurz an der Logik dran.',
      'Ich mache den Code gerade noch robuster.',
    ],
  },
  edit_docs: {
    start: [
      'Ich passe gerade den Text an.',
      'Ich ändere gerade die Notizen.',
      'Ich richte gerade die Doku aus.',
      'Ich feile gerade am Text.',
      'Ich schreibe die Anleitung gerade um.',
    ],
    steady: [
      'Ich arbeite gerade noch am Text.',
      'Ich gleiche die Doku gerade weiter ab.',
      'Ich bin noch an den Notizen dran.',
      'Ich richte die Anleitung gerade noch aus.',
      'Ich poliere den Text gerade weiter.',
    ],
    deep: [
      'Ich feile den Text noch genauer aus.',
      'Ich bringe die Doku noch sauber in Form.',
      'Ich gleiche die Notizen noch tiefer ab.',
      'Ich bleibe noch kurz an der Anleitung dran.',
      'Ich mache den Text gerade noch klarer.',
    ],
  },
  edit_settings: {
    start: [
      'Ich passe gerade die Einstellungen an.',
      'Ich ändere gerade die Konfiguration.',
      'Ich richte gerade die Config aus.',
      'Ich schraube gerade an den Einstellungen.',
      'Ich justiere gerade die Konfiguration.',
    ],
    steady: [
      'Ich arbeite gerade noch an den Einstellungen.',
      'Ich gleiche die Config gerade weiter ab.',
      'Ich bin noch an der Konfiguration dran.',
      'Ich richte die Einstellungen gerade noch aus.',
      'Ich justiere die Config gerade weiter.',
    ],
    deep: [
      'Ich feile noch an der Konfiguration.',
      'Ich bringe die Einstellungen noch sauber in Form.',
      'Ich gleiche die Config noch genauer ab.',
      'Ich bleibe noch kurz an der Konfiguration dran.',
      'Ich mache die Einstellungen gerade noch robuster.',
    ],
  },
  write_code: {
    start: [
      'Ich schreibe gerade den neuen Code.',
      'Ich baue gerade die neue Logik auf.',
      'Ich setze gerade die ersten Zeilen.',
      'Ich tippe gerade die neue Funktion ein.',
      'Ich ziehe gerade den neuen Code hoch.',
    ],
    steady: [
      'Ich schreibe den Code gerade weiter.',
      'Ich baue die Logik gerade noch aus.',
      'Ich ergänze gerade die fehlenden Teile.',
      'Ich bin noch am neuen Code dran.',
      'Ich setze den Code gerade Stück für Stück zusammen.',
    ],
    deep: [
      'Ich schreibe den Code noch sauber zu Ende.',
      'Ich baue die Logik noch fertig aus.',
      'Ich bringe den neuen Code noch in Form.',
      'Ich bleibe noch kurz am Aufbau dran.',
      'Ich ziehe die neue Funktion noch vollständig hoch.',
    ],
  },
  write_frontend: {
    start: [
      'Ich baue gerade den Oberflächenteil auf.',
      'Ich schreibe gerade die UI aus.',
      'Ich setze gerade die Ansicht auf.',
      'Ich tippe gerade den Frontend-Teil ein.',
      'Ich ziehe gerade die sichtbare Stelle hoch.',
    ],
    steady: [
      'Ich schreibe die Oberfläche gerade weiter.',
      'Ich baue die UI gerade noch aus.',
      'Ich bin noch am Frontend-Teil dran.',
      'Ich setze die Ansicht gerade weiter zusammen.',
      'Ich ergänze die sichtbare Stelle gerade noch.',
    ],
    deep: [
      'Ich schreibe die Oberfläche noch sauber zu Ende.',
      'Ich baue die UI noch fertig aus.',
      'Ich bringe die Ansicht noch in Form.',
      'Ich bleibe noch kurz am Frontend-Aufbau dran.',
      'Ich ziehe die sichtbare Stelle noch vollständig hoch.',
    ],
  },
  write_backend: {
    start: [
      'Ich baue gerade den Hintergrundteil auf.',
      'Ich schreibe gerade die Serverlogik aus.',
      'Ich setze gerade das Backend auf.',
      'Ich tippe gerade die Backend-Stelle ein.',
      'Ich ziehe gerade die Serverseite hoch.',
    ],
    steady: [
      'Ich schreibe das Backend gerade weiter.',
      'Ich baue die Serverlogik gerade noch aus.',
      'Ich bin noch am Hintergrundteil dran.',
      'Ich setze die Backend-Stelle gerade weiter zusammen.',
      'Ich ergänze die Serverseite gerade noch.',
    ],
    deep: [
      'Ich schreibe das Backend noch sauber zu Ende.',
      'Ich baue die Serverlogik noch fertig aus.',
      'Ich bringe die Backend-Stelle noch in Form.',
      'Ich bleibe noch kurz am Hintergrundteil dran.',
      'Ich ziehe die Serverseite noch vollständig hoch.',
    ],
  },
  write_styles: {
    start: [
      'Ich baue gerade das Styling auf.',
      'Ich schreibe gerade die Styles aus.',
      'Ich setze gerade die Optik auf.',
      'Ich tippe gerade die Designregeln ein.',
      'Ich ziehe gerade den Look hoch.',
    ],
    steady: [
      'Ich schreibe die Styles gerade weiter.',
      'Ich baue die Optik gerade noch aus.',
      'Ich bin noch am Styling dran.',
      'Ich setze die Designregeln gerade weiter zusammen.',
      'Ich ergänze den Look gerade noch.',
    ],
    deep: [
      'Ich schreibe das Styling noch sauber zu Ende.',
      'Ich baue die Optik noch fertig aus.',
      'Ich bringe die Styles noch in Form.',
      'Ich bleibe noch kurz am Look-Aufbau dran.',
      'Ich ziehe die Designregeln noch vollständig hoch.',
    ],
  },
  write_tests: {
    start: [
      'Ich baue gerade die Tests auf.',
      'Ich schreibe gerade die Prüflogik aus.',
      'Ich setze gerade die Testfälle auf.',
      'Ich tippe gerade die Testdatei ein.',
      'Ich ziehe gerade die Prüfstelle hoch.',
    ],
    steady: [
      'Ich schreibe die Tests gerade weiter.',
      'Ich baue die Prüflogik gerade noch aus.',
      'Ich bin noch an den Testfällen dran.',
      'Ich setze die Tests gerade weiter zusammen.',
      'Ich ergänze die Prüfstelle gerade noch.',
    ],
    deep: [
      'Ich schreibe die Tests noch sauber zu Ende.',
      'Ich baue die Prüflogik noch fertig aus.',
      'Ich bringe die Teststelle noch in Form.',
      'Ich bleibe noch kurz am Testaufbau dran.',
      'Ich ziehe die Testfälle noch vollständig hoch.',
    ],
  },
  write_docs: {
    start: [
      'Ich schreibe gerade die Notiz.',
      'Ich setze gerade die Anleitung auf.',
      'Ich tippe gerade die Doku zusammen.',
      'Ich schreibe gerade die Erklärung aus.',
      'Ich baue gerade den Text auf.',
    ],
    steady: [
      'Ich schreibe die Doku gerade weiter.',
      'Ich ergänze die Notiz gerade noch.',
      'Ich bin noch am Text dran.',
      'Ich setze die Anleitung gerade weiter zusammen.',
      'Ich arbeite die Erklärung gerade noch aus.',
    ],
    deep: [
      'Ich schreibe die Doku noch sauber zu Ende.',
      'Ich bringe den Text noch in eine klare Form.',
      'Ich ergänze die Anleitung noch vollständig.',
      'Ich bleibe noch kurz an der Erklärung dran.',
      'Ich mache die Notiz gerade noch runder.',
    ],
  },
  write_settings: {
    start: [
      'Ich schreibe gerade die Einstellungen rein.',
      'Ich lege gerade die Config an.',
      'Ich setze gerade die Konfiguration auf.',
      'Ich tippe gerade die Config zusammen.',
      'Ich baue gerade die Einstellungen auf.',
    ],
    steady: [
      'Ich schreibe die Config gerade weiter.',
      'Ich ergänze die Einstellungen gerade noch.',
      'Ich bin noch an der Konfiguration dran.',
      'Ich setze die Config gerade weiter zusammen.',
      'Ich arbeite die Einstellungen gerade noch aus.',
    ],
    deep: [
      'Ich schreibe die Config noch sauber zu Ende.',
      'Ich bringe die Einstellungen noch in Form.',
      'Ich ergänze die Konfiguration noch vollständig.',
      'Ich bleibe noch kurz an der Config dran.',
      'Ich mache das Setup gerade noch belastbar.',
    ],
  },
  search_code: {
    start: [
      'Ich suche gerade die Stelle im Code.',
      'Ich prüfe gerade, wo es im Code sitzt.',
      'Ich scanne gerade den Code ab.',
      'Ich bin gerade auf Spurensuche im Code.',
      'Ich suche gerade den passenden Codepfad.',
    ],
    steady: [
      'Ich suche im Code gerade noch weiter.',
      'Ich gleiche gerade mehrere Codestellen ab.',
      'Ich bin noch im Code auf Spur.',
      'Ich prüfe gerade noch den richtigen Treffer.',
      'Ich taste die Codestellen gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Codestellen noch gründlicher durch.',
      'Ich prüfe noch tiefer, welche Spur im Code trägt.',
      'Ich gleiche die Treffer im Code noch genauer ab.',
      'Ich bleibe noch kurz auf der Code-Spur.',
      'Ich suche noch tiefer in der Logik.',
    ],
  },
  search_frontend: {
    start: [
      'Ich suche gerade die Stelle in der Oberfläche.',
      'Ich prüfe gerade, wo es im Frontend sitzt.',
      'Ich scanne gerade die UI-Stellen ab.',
      'Ich bin gerade in der Ansicht auf Spurensuche.',
      'Ich suche gerade den passenden Frontend-Punkt.',
    ],
    steady: [
      'Ich suche in der Oberfläche gerade noch weiter.',
      'Ich gleiche gerade mehrere UI-Stellen ab.',
      'Ich bin noch im Frontend auf Spur.',
      'Ich prüfe gerade noch den richtigen Ansichtstreffer.',
      'Ich taste die UI-Stellen gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Oberflächenstellen noch gründlicher durch.',
      'Ich prüfe noch tiefer, welche UI-Spur trägt.',
      'Ich gleiche die Frontend-Treffer noch genauer ab.',
      'Ich bleibe noch kurz auf der Frontend-Spur.',
      'Ich suche noch tiefer in der Ansicht.',
    ],
  },
  search_backend: {
    start: [
      'Ich suche gerade die Stelle im Backend.',
      'Ich prüfe gerade, wo es auf der Serverseite sitzt.',
      'Ich scanne gerade die Backend-Stellen ab.',
      'Ich bin gerade im Hintergrundteil auf Spurensuche.',
      'Ich suche gerade den passenden Serverpunkt.',
    ],
    steady: [
      'Ich suche im Backend gerade noch weiter.',
      'Ich gleiche gerade mehrere Serverstellen ab.',
      'Ich bin noch auf der Backend-Spur.',
      'Ich prüfe gerade noch den richtigen Hintergrundtreffer.',
      'Ich taste die Serverstellen gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Backend-Stellen noch gründlicher durch.',
      'Ich prüfe noch tiefer, welche Serverspur trägt.',
      'Ich gleiche die Hintergrundtreffer noch genauer ab.',
      'Ich bleibe noch kurz auf der Backend-Spur.',
      'Ich suche noch tiefer auf der Serverseite.',
    ],
  },
  search_styles: {
    start: [
      'Ich suche gerade die Style-Stelle.',
      'Ich prüfe gerade, wo die Optik geregelt ist.',
      'Ich scanne gerade die Styles ab.',
      'Ich bin gerade im Styling auf Spurensuche.',
      'Ich suche gerade die passende Designstelle.',
    ],
    steady: [
      'Ich suche in den Styles gerade noch weiter.',
      'Ich gleiche gerade mehrere Optik-Stellen ab.',
      'Ich bin noch auf der Style-Spur.',
      'Ich prüfe gerade noch den richtigen Designtreffer.',
      'Ich taste die Styles gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Styles noch gründlicher durch.',
      'Ich prüfe noch tiefer, wo die Optik wirklich sitzt.',
      'Ich gleiche die Designtreffer noch genauer ab.',
      'Ich bleibe noch kurz auf der Style-Spur.',
      'Ich suche noch tiefer im Styling.',
    ],
  },
  search_tests: {
    start: [
      'Ich suche gerade die passende Teststelle.',
      'Ich prüfe gerade, wo das schon getestet wird.',
      'Ich scanne gerade die Tests ab.',
      'Ich bin gerade in den Testfällen auf Spurensuche.',
      'Ich suche gerade den passenden Prüftreffer.',
    ],
    steady: [
      'Ich suche in den Tests gerade noch weiter.',
      'Ich gleiche gerade mehrere Teststellen ab.',
      'Ich bin noch auf der Prüfspur.',
      'Ich prüfe gerade noch den richtigen Testtreffer.',
      'Ich taste die Tests gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Tests noch gründlicher durch.',
      'Ich prüfe noch tiefer, wo es schon abgesichert ist.',
      'Ich gleiche die Prüftreffer noch genauer ab.',
      'Ich bleibe noch kurz auf der Testspur.',
      'Ich suche noch tiefer in den Testfällen.',
    ],
  },
  search_files: {
    start: [
      'Ich suche gerade die passende Datei.',
      'Ich prüfe gerade, wo die Datei liegt.',
      'Ich gehe gerade auf Dateisuche.',
      'Ich scanne gerade die Ordner ab.',
      'Ich suche gerade den richtigen Dateipfad.',
    ],
    steady: [
      'Ich suche gerade noch die passende Datei.',
      'Ich gleiche gerade mehrere Pfade ab.',
      'Ich bin noch in den Ordnern unterwegs.',
      'Ich prüfe gerade noch den richtigen Pfad.',
      'Ich taste die Dateiliste gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Dateipfade noch gründlicher durch.',
      'Ich prüfe noch tiefer, wo die richtige Datei sitzt.',
      'Ich gleiche die Ordnerstruktur noch genauer ab.',
      'Ich bleibe noch kurz auf Dateisuche.',
      'Ich suche noch tiefer in den Pfaden.',
    ],
  },
  search_docs: {
    start: [
      'Ich suche gerade die passende Notiz.',
      'Ich prüfe gerade, wo es in der Doku steht.',
      'Ich gehe gerade die Texte auf Spur ab.',
      'Ich suche gerade die richtige Stelle in den Notizen.',
      'Ich scanne gerade die Doku ab.',
    ],
    steady: [
      'Ich suche in der Doku gerade noch weiter.',
      'Ich gleiche gerade mehrere Notizen ab.',
      'Ich bin noch in den Texten unterwegs.',
      'Ich prüfe gerade noch die richtige Doku-Stelle.',
      'Ich taste die Notizen gerade weiter ab.',
    ],
    deep: [
      'Ich gehe die Doku noch gründlicher durch.',
      'Ich prüfe noch tiefer, wo es wirklich steht.',
      'Ich gleiche die Notizen noch genauer ab.',
      'Ich bleibe noch kurz in den Texten dran.',
      'Ich suche noch tiefer in der Doku.',
    ],
  },
  exec_build: {
    start: [
      'Ich stoße gerade den Build an.',
      'Ich prüfe gerade, ob alles baut.',
      'Ich lasse gerade den Build laufen.',
      'Ich werfe gerade den Bau-Check an.',
      'Ich teste gerade, ob die App sauber baut.',
    ],
    steady: [
      'Ich lasse den Build gerade noch laufen.',
      'Ich prüfe gerade noch, ob alles sauber baut.',
      'Ich warte gerade noch auf den Build.',
      'Ich halte den Bau-Check noch offen.',
      'Ich bin noch beim Build dran.',
    ],
    deep: [
      'Ich prüfe den Build noch gründlicher.',
      'Ich warte noch, bis der Build sauber durch ist.',
      'Ich halte den Build noch unter Beobachtung.',
      'Ich bleibe noch kurz beim Bau-Check.',
      'Ich prüfe noch, ob beim Build wirklich Ruhe ist.',
    ],
  },
  exec_test: {
    start: [
      'Ich starte gerade den Testlauf.',
      'Ich prüfe gerade mit Tests nach.',
      'Ich lasse gerade die Tests laufen.',
      'Ich werfe gerade den Gegencheck an.',
      'Ich teste gerade, ob alles hält.',
    ],
    steady: [
      'Ich lasse die Tests gerade noch laufen.',
      'Ich prüfe gerade noch die Rückmeldung der Tests.',
      'Ich warte gerade noch auf den Testlauf.',
      'Ich halte den Gegencheck noch offen.',
      'Ich bin noch im Testlauf dran.',
    ],
    deep: [
      'Ich prüfe die Tests noch gründlicher.',
      'Ich warte noch, bis der Testlauf sauber durch ist.',
      'Ich halte die Tests noch unter Beobachtung.',
      'Ich bleibe noch kurz im Gegencheck.',
      'Ich prüfe noch, ob die Tests wirklich Ruhe geben.',
    ],
  },
  exec_lint: {
    start: [
      'Ich starte gerade den Code-Check.',
      'Ich prüfe gerade Stil und Sauberkeit.',
      'Ich lasse gerade den Lintlauf laufen.',
      'Ich werfe gerade den Sauberkeitscheck an.',
      'Ich teste gerade, ob der Code ruhig bleibt.',
    ],
    steady: [
      'Ich lasse den Code-Check gerade noch laufen.',
      'Ich prüfe gerade noch die Rückmeldung vom Lintlauf.',
      'Ich warte gerade noch auf den Sauberkeitscheck.',
      'Ich halte den Code-Check noch offen.',
      'Ich bin noch am Lintlauf dran.',
    ],
    deep: [
      'Ich prüfe den Code-Check noch gründlicher.',
      'Ich warte noch, bis der Lintlauf sauber durch ist.',
      'Ich halte den Sauberkeitscheck noch unter Beobachtung.',
      'Ich bleibe noch kurz beim Code-Check.',
      'Ich prüfe noch, ob der Code dabei wirklich ruhig bleibt.',
    ],
  },
  exec_git: {
    start: [
      'Ich schaue gerade in den Git-Stand.',
      'Ich prüfe gerade die Änderungen.',
      'Ich sehe mir gerade den Diff an.',
      'Ich werfe gerade einen Blick auf Git.',
      'Ich prüfe gerade den Versionsstand.',
    ],
    steady: [
      'Ich gleiche den Git-Stand gerade noch ab.',
      'Ich prüfe die Änderungen gerade weiter.',
      'Ich bin noch im Diff unterwegs.',
      'Ich sehe mir Git gerade noch genauer an.',
      'Ich halte den Versionsstand noch kurz offen.',
    ],
    deep: [
      'Ich prüfe die Änderungen noch gründlicher.',
      'Ich gehe den Git-Stand noch sauber durch.',
      'Ich gleiche den Diff noch genauer ab.',
      'Ich bleibe noch kurz im Versionsstand dran.',
      'Ich prüfe Git noch bis ins Detail.',
    ],
  },
  exec_server: {
    start: [
      'Ich starte gerade den Dienst an.',
      'Ich prüfe gerade den Serverlauf.',
      'Ich kümmere mich gerade um den Start.',
      'Ich stoße gerade den Dienst an.',
      'Ich prüfe gerade, ob der Server hochkommt.',
    ],
    steady: [
      'Ich warte gerade noch auf den Dienst.',
      'Ich prüfe den Server gerade weiter.',
      'Ich bin noch beim Startlauf dran.',
      'Ich halte den Dienst gerade noch im Blick.',
      'Ich warte gerade noch, bis der Server sauber läuft.',
    ],
    deep: [
      'Ich prüfe den Dienst noch gründlicher.',
      'Ich warte noch, bis der Server stabil steht.',
      'Ich halte den Start noch unter Beobachtung.',
      'Ich bleibe noch kurz am Dienst dran.',
      'Ich prüfe noch, ob der Server wirklich sauber läuft.',
    ],
  },
  agent_review: {
    start: [
      'Ich hole gerade noch eine zweite Meinung dazu.',
      'Ich lasse gerade noch einmal draufschauen.',
      'Ich ziehe gerade eine zweite Meinung rein.',
      'Ich hole gerade noch eine Rückversicherung dazu.',
      'Ich prüfe das gerade noch einmal extra ab.',
    ],
    steady: [
      'Ich sammle gerade noch die zweite Meinung ein.',
      'Ich lasse die Rückversicherung gerade noch laufen.',
      'Ich bin noch bei der zweiten Meinung dran.',
      'Ich gleiche gerade noch die zweite Meinung ab.',
      'Ich warte gerade noch auf die Rückversicherung.',
    ],
    deep: [
      'Ich prüfe das noch mit einer gründlicheren zweiten Meinung.',
      'Ich halte die Rückversicherung noch etwas länger offen.',
      'Ich gleiche die zweite Meinung noch genauer ab.',
      'Ich bleibe noch kurz bei der zweiten Meinung.',
      'Ich prüfe noch, ob die zweite Meinung dieselbe Linie sieht.',
    ],
  },
  web_search: {
    start: [
      'Ich suche gerade im Web nach dem Stand.',
      'Ich prüfe gerade das Web auf aktuelle Infos.',
      'Ich schaue gerade nach frischen Quellen.',
      'Ich suche gerade die aktuelle Antwort im Web.',
      'Ich hole gerade frische Webinfos rein.',
    ],
    steady: [
      'Ich suche im Web gerade noch weiter.',
      'Ich gleiche gerade mehrere Webquellen ab.',
      'Ich bin noch bei den aktuellen Infos dran.',
      'Ich prüfe gerade noch den frischesten Stand.',
      'Ich taste die Webquellen gerade weiter ab.',
    ],
    deep: [
      'Ich prüfe die Webquellen noch gründlicher.',
      'Ich gleiche den Stand im Web noch genauer ab.',
      'Ich bleibe noch kurz bei den Quellen dran.',
      'Ich prüfe noch tiefer, was heute wirklich gilt.',
      'Ich suche noch nach der belastbarsten Quelle.',
    ],
  },
  web_fetch: {
    start: [
      'Ich öffne gerade die Seite.',
      'Ich lade gerade die Webseite an.',
      'Ich ziehe gerade den Seiteninhalt rein.',
      'Ich schaue gerade in die Seite rein.',
      'Ich hole gerade den Inhalt der Webseite.',
    ],
    steady: [
      'Ich lese die Seite gerade noch aus.',
      'Ich bin noch im Seiteninhalt dran.',
      'Ich prüfe die Webseite gerade weiter.',
      'Ich ziehe die Seite gerade noch vollständig rein.',
      'Ich gehe die Webseite gerade noch durch.',
    ],
    deep: [
      'Ich prüfe die Webseite noch gründlicher.',
      'Ich lese die Seite noch sauber zu Ende aus.',
      'Ich bleibe noch kurz im Seiteninhalt dran.',
      'Ich ziehe noch tiefer durch die Webseite.',
      'Ich prüfe noch genauer, was auf der Seite wirklich steht.',
    ],
  },
  todo_plan: {
    start: [
      'Ich sortiere gerade die nächsten Schritte.',
      'Ich stelle gerade den Fahrplan auf.',
      'Ich ordne gerade die nächsten Punkte.',
      'Ich bringe gerade Reihenfolge rein.',
      'Ich plane gerade den nächsten Zug.',
    ],
    steady: [
      'Ich sortiere die nächsten Schritte gerade weiter.',
      'Ich gleiche den Fahrplan gerade noch ab.',
      'Ich bin noch bei der Reihenfolge dran.',
      'Ich ordne die nächsten Punkte gerade noch.',
      'Ich halte den Plan gerade noch kurz offen.',
    ],
    deep: [
      'Ich ziehe den Plan noch genauer gerade.',
      'Ich sortiere die Reihenfolge noch gründlicher.',
      'Ich bleibe noch kurz am Fahrplan dran.',
      'Ich prüfe noch, was zuerst wirklich Sinn ergibt.',
      'Ich bringe den Plan noch sauber in Form.',
    ],
  },
}

export const TOOL_SUBTYPE_PHRASES: Record<string, Record<ToolPhrasePhase, string[]>> = {
  ...EXPLICIT_SUBTYPE_PHRASES,
  ...createGeneratedSubtypePhrases(),
  ...EXTRA_EXEC_PHRASES,
}
