export type ToolPhraseKind = 'read' | 'edit' | 'write' | 'search' | 'exec' | 'agent' | 'web' | 'todo' | 'other'
export type ToolPhrasePhase = 'start' | 'steady' | 'deep'

export const TOOL_PHRASES: Record<ToolPhraseKind, Record<ToolPhrasePhase, string[]>> = {
  read: {
    start: [
      'Ich schaue gerade {place} nach.',
      'Ich lese mich gerade in {place} ein.',
      'Ich blättere gerade durch {place}.',
      'Ich taste mich gerade {place} heran.',
      'Ich orientiere mich gerade {place}.',
      'Ich überfliege gerade {place}.',
      'Ich gehe gerade erst einmal {place} rein.',
      'Ich prüfe gerade, was {place} wirklich passiert.',
      'Ich sammle gerade {place} die ersten Signale ein.',
      'Ich klemme mich gerade kurz hinter {place}.',
      'Ich lese gerade an {place} die Fährte an.',
      'Ich halte gerade {place} nach der relevanten Ecke Ausschau.',
    ],
    steady: [
      'Ich bin noch {place} und gleiche die Stellen ab.',
      'Ich lese {place} weiter, damit die Änderung sauber sitzt.',
      'Ich prüfe {place} noch auf die genaue Stelle.',
      'Ich suche {place} noch den richtigen Punkt.',
      'Ich bin noch {place}, um die Lage sauber einzugrenzen.',
      'Ich gehe {place} weiter Zeile für Zeile durch.',
      'Ich bin noch {place} und sortiere die Zusammenhänge.',
      'Ich gleiche {place} gerade noch gegen ähnliche Stellen ab.',
      'Ich prüfe {place} weiter, damit später nichts verrutscht.',
      'Ich lese {place} noch quer, bevor ich Hand anlege.',
      'Ich bin noch {place} und sammele die letzten Puzzleteile.',
      'Ich verfolge {place} noch die Spur bis zur Ursache.',
    ],
    deep: [
      'Ich bin noch {place} unterwegs, damit ich die Stelle wirklich sauber treffe.',
      'Ich lese {place} weiter, weil ich vor dem Ändern nichts übersehen will.',
      'Ich bin noch {place} und gleiche die Zusammenhänge sorgfältig ab.',
      'Ich prüfe {place} noch tiefer, damit der Eingriff nachher sitzt.',
      'Ich gehe {place} noch einmal gründlich durch, bevor ich etwas anfasse.',
      'Ich bleibe noch {place}, bis die Logik komplett klar ist.',
      'Ich lese {place} noch einmal gegen den Strich, damit kein Detail kippt.',
      'Ich bohre mich noch tiefer {place} hinein.',
      'Ich sammele {place} gerade noch die letzte Restgewissheit ein.',
      'Ich bin noch {place}, bis die Stelle sich wirklich erklärt.',
      'Ich halte noch kurz {place} die Taschenlampe drauf.',
      'Ich gehe {place} noch einmal mit Nerd-Brille durch.',
    ],
  },
  edit: {
    start: [
      'Ich passe gerade {target} an.',
      'Ich schraube gerade an {target}.',
      'Ich tüftle gerade an {target}.',
      'Ich lege gerade Hand an {target}.',
      'Ich feile gerade an {target}.',
      'Ich rücke {target} gerade zurecht.',
      'Ich baue {target} gerade um.',
      'Ich setze gerade den ersten Eingriff in {target}.',
      'Ich mache mich gerade über {target} her.',
      'Ich ziehe {target} gerade in die richtige Richtung.',
      'Ich justiere gerade {target}.',
      'Ich drehe gerade an {target} die richtigen Schrauben.',
    ],
    steady: [
      'Ich ändere {target} gerade noch an der richtigen Stelle.',
      'Ich bin noch dabei, {target} passend umzubauen.',
      'Ich arbeite weiter an {target}, damit die Änderung sauber landet.',
      'Ich setze die Änderung in {target} gerade Stück für Stück ein.',
      'Ich gleiche {target} gerade noch an, damit alles zusammenpasst.',
      'Ich runde {target} gerade noch ab.',
      'Ich bin noch mitten in {target} und richte die Kanten aus.',
      'Ich ziehe {target} gerade noch sauber gerade.',
      'Ich poliere {target} noch in Form.',
      'Ich schiebe {target} gerade noch in die saubere Spur.',
      'Ich bin noch an {target}, bis es sich stimmig anfühlt.',
      'Ich arbeite {target} gerade noch in den Takt ein.',
    ],
    deep: [
      'Ich arbeite noch an {target}, damit die Änderung sauber sitzt.',
      'Ich bin noch mitten in {target}, weil ich den Umbau ordentlich ausrichte.',
      'Ich passe {target} weiter an und gleiche die Änderung sauber ein.',
      'Ich bin noch in {target}, damit die Änderung nicht nur schnell, sondern stimmig sitzt.',
      'Ich feile noch an {target}, damit am Ende alles zusammenpasst.',
      'Ich bleibe noch an {target}, bis die Kante wirklich sauber ist.',
      'Ich bin noch bei {target}, weil gerade die feinen Stellen drankommen.',
      'Ich tune {target} gerade noch auf ruhig und robust.',
      'Ich bin noch an {target}, damit die Änderung nicht nur hält, sondern gut aussieht.',
      'Ich richte {target} noch einmal präzise aus.',
      'Ich arbeite {target} noch auf die elegante Lösung hin.',
      'Ich mache {target} gerade noch resistent gegen Folgebugs.',
    ],
  },
  write: {
    start: [
      'Ich schreibe gerade {target}.',
      'Ich lege gerade {target} an.',
      'Ich tippe gerade {target} zusammen.',
      'Ich gieße {target} gerade frisch ins Reine.',
      'Ich bringe {target} gerade aufs Papier.',
      'Ich baue gerade {target} auf.',
      'Ich fülle gerade {target} mit der neuen Fassung.',
      'Ich setze gerade die ersten Zeilen in {target}.',
      'Ich ziehe {target} gerade neu hoch.',
      'Ich schreibe {target} gerade aus dem Kopf in den Code.',
      'Ich beginne gerade {target} sauber aufzubauen.',
      'Ich lege {target} gerade in brauchbar an.',
    ],
    steady: [
      'Ich schreibe {target} gerade weiter.',
      'Ich ergänze {target} noch um die fehlenden Teile.',
      'Ich fülle {target} gerade sauber auf.',
      'Ich bin noch dabei, {target} fertig aufzubauen.',
      'Ich setze {target} gerade Stück für Stück zusammen.',
      'Ich schreibe {target} gerade weiter in Form.',
      'Ich ziehe {target} gerade noch vollständig hoch.',
      'Ich baue {target} noch mit den fehlenden Kanten aus.',
      'Ich gieße {target} gerade noch in eine saubere Fassung.',
      'Ich hänge {target} gerade noch die wichtigen Teile an.',
      'Ich bin noch an {target}, bis alles Wichtige drin ist.',
      'Ich füttere {target} gerade noch mit Substanz.',
    ],
    deep: [
      'Ich schreibe noch an {target}, damit die neue Fassung sauber steht.',
      'Ich arbeite noch an {target}, weil ich die neue Struktur vollständig einziehe.',
      'Ich ergänze {target} weiter, damit dort gleich alles Nötige zusammenliegt.',
      'Ich bin noch an {target}, damit die neue Datei vollständig nutzbar ist.',
      'Ich baue {target} gerade noch fertig auf.',
      'Ich schreibe {target} noch zu Ende, damit später nichts fehlt.',
      'Ich bleibe noch an {target}, bis die neue Form wirklich rund ist.',
      'Ich bringe {target} gerade noch in die endgültige Fassung.',
      'Ich schichte {target} noch sauber zusammen.',
      'Ich ziehe {target} noch bis zur letzten brauchbaren Zeile durch.',
      'Ich tippe {target} noch mit der finalen Logik voll.',
      'Ich schreibe {target} noch so fertig, dass es direkt tragen kann.',
    ],
  },
  search: {
    start: [
      'Ich suche gerade die richtige Stelle im Code.',
      'Ich prüfe gerade, wo die passende Stelle sitzt.',
      'Ich scanne den Code gerade nach der richtigen Ecke ab.',
      'Ich suche gerade den Punkt, an dem ich sauber ansetzen kann.',
      'Ich sortiere gerade aus, welche Stelle hier die relevante ist.',
      'Ich schnuppere gerade in den Codewald rein.',
      'Ich jage gerade die richtige Fährte durch den Code.',
      'Ich suche gerade die Nadel im Stack.',
      'Ich gehe gerade auf Spurensuche im Code.',
      'Ich prüfe gerade, wo die Sache wirklich andockt.',
      'Ich funke gerade die relevante Stelle an.',
      'Ich halte gerade den Suchscheinwerfer auf den Code.',
    ],
    steady: [
      'Ich suche gerade noch die richtige Stelle im Code.',
      'Ich prüfe noch, wo genau die Änderung hingehört.',
      'Ich gleiche gerade ähnliche Stellen ab, damit ich die richtige erwische.',
      'Ich bin noch dabei, die passende Code-Stelle einzugrenzen.',
      'Ich prüfe gerade noch, welche Stelle hier wirklich zuständig ist.',
      'Ich hänge noch in der Code-Spur und gleiche Kandidaten ab.',
      'Ich suche gerade noch, welcher Pfad hier wirklich zieht.',
      'Ich gleiche gerade noch mehrere Treffer gegeneinander ab.',
      'Ich bin noch am Filtern, welche Stelle kein Blendwerk ist.',
      'Ich prüfe noch, welche Spur im Code nicht ins Leere läuft.',
      'Ich bin noch im Suchmodus und ziehe die falschen Fährten raus.',
      'Ich taste gerade noch ab, welcher Treffer Substanz hat.',
    ],
    deep: [
      'Ich suche noch die genaue Stelle im Code, damit ich nichts Falsches erwische.',
      'Ich bin noch im Code unterwegs und gleiche ähnliche Stellen gegeneinander ab.',
      'Ich prüfe noch mehrere Stellen, damit ich wirklich die richtige treffe.',
      'Ich suche noch tiefer, weil ich die Änderung sauber verankern will.',
      'Ich bin noch beim Einordnen, welche Stelle im Code wirklich zuständig ist.',
      'Ich bleibe noch auf der Spur, bis klar ist, welcher Treffer trägt.',
      'Ich gehe noch tiefer in die Treffer rein, damit nichts zufällig wirkt.',
      'Ich mappe gerade noch, welcher Codepfad die Wahrheit sagt.',
      'Ich bin noch im Detektivmodus und nehme die falschen Verdächtigen raus.',
      'Ich folge gerade noch dem Brotkrumenpfad durch den Stack.',
      'Ich suche noch eine Ebene tiefer, damit der Eingriff später exakt sitzt.',
      'Ich grabe noch tiefer, bis nur die echte Stelle übrig bleibt.',
    ],
  },
  exec: {
    start: [
      'Ich prüfe das gerade kurz im Terminal.',
      'Ich lasse gerade einen schnellen Check laufen.',
      'Ich teste die Stelle gerade kurz an.',
      'Ich prüfe gerade praktisch nach, ob das so greift.',
      'Ich lasse gerade kurz gegenlaufen, ob alles passt.',
      'Ich werfe gerade einen schnellen Maschinenblick drauf.',
      'Ich stoße gerade den ersten Check an.',
      'Ich schicke das gerade einmal durch den Prüfstand.',
      'Ich lasse gerade kurz den Rechner meckern oder nicken.',
      'Ich taste die Stelle gerade technisch an.',
      'Ich lasse gerade einen kleinen Smoke-Test los.',
      'Ich prüfe gerade, ob der Build mich auslacht.',
    ],
    steady: [
      'Ich lasse gerade noch einen Check laufen.',
      'Ich prüfe die Stelle gerade noch einmal praktisch nach.',
      'Ich teste gerade weiter, ob alles sauber greift.',
      'Ich bin noch beim kurzen Gegencheck.',
      'Ich lasse gerade noch verifizieren, dass die Stelle sauber läuft.',
      'Ich bin noch im Testlauf und gleiche die Rückmeldung ab.',
      'Ich lasse gerade noch die technische Ehrenrunde drehen.',
      'Ich prüfe gerade noch, ob der Pfad unter Last sauber bleibt.',
      'Ich bin noch im Maschinenraum und höre auf Nebengeräusche.',
      'Ich teste gerade noch, ob die Änderung wirklich ruhig läuft.',
      'Ich halte den Check noch kurz offen.',
      'Ich warte gerade noch auf das saubere Nicken vom System.',
    ],
    deep: [
      'Ich lasse gerade noch einen gründlicheren Check laufen.',
      'Ich prüfe die Stelle gerade weiter, damit ich das Ergebnis absichern kann.',
      'Ich teste gerade noch nach, ob alles stabil durchläuft.',
      'Ich bin noch beim Gegencheck, damit die Änderung nicht nur gut aussieht, sondern auch hält.',
      'Ich lasse gerade noch prüfen, ob sich die Änderung sauber verhält.',
      'Ich bleibe noch im Prüfmodus, bis das sauber belastbar ist.',
      'Ich lasse das gerade noch einmal tief durchsieben.',
      'Ich prüfe noch eine Runde härter nach, damit später nichts kippt.',
      'Ich halte den Test noch offen, bis wirklich Ruhe ist.',
      'Ich bin noch im Validieren, damit der nächste Schritt nicht blind ist.',
      'Ich lasse gerade noch die nerdige Kontrollrunde drüberlaufen.',
      'Ich prüfe noch, ob das auch unter der Haube vernünftig bleibt.',
    ],
  },
  agent: {
    start: [
      'Ich hole gerade noch eine zweite Meinung dazu.',
      'Ich lasse die Stelle gerade kurz gegenprüfen.',
      'Ich ziehe gerade noch eine zweite Meinung dazu.',
      'Ich schaue gerade, ob die zweite Meinung dieselbe Richtung sieht.',
      'Ich lasse das gerade kurz von einer zweiten Seite abklopfen.',
      'Ich schicke das gerade durch ein zweites Gehirn.',
      'Ich hole gerade eine Extra-Runde Plausibilität rein.',
      'Ich gebe die Stelle gerade kurz weiter zum Gegenlesen.',
      'Ich ziehe gerade noch Backup fürs Denken dazu.',
      'Ich hole gerade einen kleinen Peer-Review-Moment rein.',
      'Ich lasse gerade noch eine Rückversicherung drüberschauen.',
      'Ich funke gerade die zweite Meinung an.',
    ],
    steady: [
      'Ich hole gerade noch eine zweite Meinung dazu.',
      'Ich lasse die Stelle gerade noch gegenprüfen.',
      'Ich ziehe gerade noch eine zweite Meinung dazu.',
      'Ich lasse gerade noch einmal unabhängig draufschauen.',
      'Ich prüfe die Richtung gerade noch mit einer zweiten Meinung ab.',
      'Ich bin noch im Abgleich mit einem zweiten Kopf.',
      'Ich halte die Stelle noch kurz unter doppelter Beobachtung.',
      'Ich bin noch dabei, die zweite Meinung sauber einzusammeln.',
      'Ich gleiche gerade noch ab, ob die zweite Meinung dieselbe Linie sieht.',
      'Ich lasse die zweite Meinung noch kurz zu Ende laufen.',
      'Ich bin noch im Gegenlesen, damit nichts schief hängt.',
      'Ich prüfe gerade noch, ob der Querblick mitzieht.',
    ],
    deep: [
      'Ich habe noch eine zweite Meinung drauf, damit die Einschätzung nicht zu schnell wird.',
      'Ich lasse die Stelle noch gegenprüfen, bevor ich mich festlege.',
      'Ich hole gerade weiter eine zweite Meinung dazu ein.',
      'Ich bin noch bei der zweiten Meinung, damit die Richtung wirklich belastbar ist.',
      'Ich lasse das gerade noch einmal unabhängig querprüfen.',
      'Ich bleibe noch im Vier-Augen-Modus, bis die Linie trägt.',
      'Ich hole noch Tiefe aus der zweiten Meinung raus.',
      'Ich lasse die Stelle noch weiter abklopfen, damit nichts nur Bauchgefühl bleibt.',
      'Ich bin noch im Quercheck, bis die Richtung mehr als nur plausibel ist.',
      'Ich prüfe noch, ob der zweite Kopf denselben Bug riecht.',
      'Ich lasse den Gegenblick noch ausreden, bevor ich weiterziehe.',
      'Ich halte noch kurz zwei Denkrichtungen gegeneinander.',
    ],
  },
  web: {
    start: [
      'Ich prüfe gerade kurz im Web, was aktuell der Stand ist.',
      'Ich schaue gerade nach der aktuellen Antwort.',
      'Ich hole gerade den frischen Stand dazu rein.',
      'Ich prüfe gerade, was dazu heute wirklich gilt.',
      'Ich schaue gerade kurz nach, damit die Antwort aktuell bleibt.',
      'Ich ziehe gerade frische Webspuren dazu.',
      'Ich klopfe gerade kurz das Netz auf aktuelle Signale ab.',
      'Ich prüfe gerade, was draußen im Web wirklich los ist.',
      'Ich fische gerade den aktuellen Stand aus dem Netz.',
      'Ich hole gerade die heutige Lage dazu rein.',
      'Ich schaue gerade nach, ob sich da frisch etwas bewegt hat.',
      'Ich mache gerade einen kleinen Web-Realitätscheck.',
    ],
    steady: [
      'Ich schaue gerade noch nach der aktuellen Antwort.',
      'Ich prüfe im Web gerade noch den genauen Stand.',
      'Ich gleiche gerade noch ab, was dazu aktuell gilt.',
      'Ich bin noch beim Nachsehen, damit die Antwort frisch ist.',
      'Ich prüfe gerade noch, welche aktuelle Quelle hier am besten trägt.',
      'Ich gleiche gerade noch mehrere Quellen gegeneinander ab.',
      'Ich bin noch dabei, den frischesten Stand rauszuziehen.',
      'Ich schaue gerade noch, welche Quelle hier am saubersten bleibt.',
      'Ich halte gerade noch die Weblage gegen eine zweite Quelle.',
      'Ich bin noch im Nachsehen, damit nichts von gestern durchrutscht.',
      'Ich suche noch, welche Quelle hier wirklich Substanz hat.',
      'Ich klopfe gerade noch die Webspuren auf Aktualität ab.',
    ],
    deep: [
      'Ich prüfe gerade noch mehrere Quellen, damit der Stand wirklich aktuell ist.',
      'Ich gleiche gerade noch ab, was im Web wirklich der aktuelle Stand ist.',
      'Ich bin noch beim Nachsehen, damit ich dir nichts Veraltetes gebe.',
      'Ich prüfe gerade weiter, welche Quelle hier die sauberste Antwort liefert.',
      'Ich suche gerade noch nach einer belastbaren aktuellen Antwort.',
      'Ich bleibe noch im Web, bis sich die Quellen sauber decken.',
      'Ich bin noch beim Abgleich, damit hier nicht nur die lauteste Quelle gewinnt.',
      'Ich prüfe noch tiefer, was davon wirklich heute trägt.',
      'Ich gehe die Weblage noch eine Runde gründlicher ab.',
      'Ich sammle noch die belastbaren Krümel aus mehreren Quellen ein.',
      'Ich lasse gerade noch keinen alten Link durchrutschen.',
      'Ich halte noch kurz die Quellen unter Aktualitätsstress.',
    ],
  },
  todo: {
    start: [
      'Ich sortiere gerade die nächsten Schritte.',
      'Ich halte gerade kurz die To dos fest.',
      'Ich bringe gerade Ordnung in die nächsten Schritte.',
      'Ich lege gerade fest, was als Nächstes dran ist.',
      'Ich sammle gerade die nächsten Schritte zusammen.',
      'Ich baue gerade die Reihenfolge zusammen.',
      'Ich ziehe gerade die nächsten Punkte auf Linie.',
      'Ich stecke gerade den Fahrplan ab.',
      'Ich ordne gerade die Baustellen in sinnvoll.',
      'Ich sortiere gerade das Nächste zuerst.',
      'Ich packe gerade Ordnung in die Aufgaben.',
      'Ich pinne gerade die nächsten Schritte fest.',
    ],
    steady: [
      'Ich sortiere gerade noch die nächsten Schritte.',
      'Ich halte gerade weiter fest, was als Nächstes dran ist.',
      'Ich bringe die nächsten Schritte gerade noch in Ordnung.',
      'Ich ordne gerade noch, was zuerst passieren sollte.',
      'Ich bin noch dabei, die nächsten Schritte sauber festzuhalten.',
      'Ich feile noch an der Reihenfolge der nächsten Punkte.',
      'Ich räume die nächsten Schritte gerade noch in die richtige Spur.',
      'Ich sortiere noch nach, was zuerst Luft braucht.',
      'Ich bringe die To dos gerade noch in einen sinnvollen Takt.',
      'Ich ordne gerade noch die nächste Schleife sauber ein.',
      'Ich halte die Reihenfolge noch kurz unter Kontrolle.',
      'Ich richte gerade noch die nächsten Punkte aus.',
    ],
    deep: [
      'Ich ordne die nächsten Schritte noch sauber, damit die Reihenfolge wirklich Sinn ergibt.',
      'Ich bin noch dabei, die nächsten Schritte klar zu sortieren.',
      'Ich bringe die nächsten Schritte noch in eine saubere Reihenfolge.',
      'Ich halte die nächsten Schritte noch so fest, dass sie gleich wirklich tragen.',
      'Ich sortiere noch nach, was zuerst und was später kommen sollte.',
      'Ich bleibe noch in der Reihenfolge, bis kein Punkt mehr querliegt.',
      'Ich ziehe die nächsten Schritte noch in eine belastbare Linie.',
      'Ich richte den Fahrplan noch so aus, dass nichts unnötig kollidiert.',
      'Ich sortiere noch, damit der nächste Move nicht nur schnell, sondern klug ist.',
      'Ich bin noch beim Priorisieren, bis die Abfolge wirklich ruhig ist.',
      'Ich bringe die nächsten Punkte noch in eine nervenschonende Logik.',
      'Ich halte die To dos noch kurz unter Architekturaufsicht.',
    ],
  },
  other: {
    start: [
      'Ich arbeite gerade an der nächsten Stelle.',
      'Ich gehe gerade in den nächsten Schritt rein.',
      'Ich bin gerade an der passenden Stelle dran.',
      'Ich ordne gerade den nächsten Schritt ein.',
      'Ich arbeite gerade die nächste Stelle sauber auf.',
      'Ich bin gerade am nächsten sinnvollen Zug.',
      'Ich halte gerade den nächsten Schritt fest.',
      'Ich gehe gerade den nächsten Haken an.',
      'Ich sortiere gerade den nächsten Move.',
      'Ich bin gerade an der nächsten brauchbaren Ecke.',
      'Ich ziehe gerade den nächsten Faden an.',
      'Ich setze gerade beim nächsten sinnvollen Punkt an.',
    ],
    steady: [
      'Ich arbeite gerade noch an der nächsten Stelle.',
      'Ich bin noch mitten im Schritt und gleiche die passende Richtung ab.',
      'Ich gehe gerade weiter durch den nächsten Arbeitsschritt.',
      'Ich bin noch dabei, die Stelle sauber einzuordnen.',
      'Ich arbeite gerade weiter, damit der nächste Schritt sitzt.',
      'Ich bin noch am nächsten Punkt dran und halte ihn ruhig auf Kurs.',
      'Ich arbeite den nächsten Schritt gerade noch sauber ab.',
      'Ich hänge noch am nächsten Abschnitt und richte ihn aus.',
      'Ich bin noch dabei, den nächsten Zug ordentlich zu setzen.',
      'Ich gehe noch eine Runde durch den aktuellen Schritt.',
      'Ich arbeite noch an der passenden Linie für den nächsten Move.',
      'Ich halte die aktuelle Stelle noch kurz zusammen.',
    ],
    deep: [
      'Ich bin noch an der Stelle dran und gleiche gerade die Details ab.',
      'Ich arbeite gerade weiter daran, damit am Ende alles sauber sitzt.',
      'Ich bin noch mitten im Schritt und sortiere die letzten offenen Punkte.',
      'Ich prüfe die Stelle gerade noch tiefer, bevor ich weitergehe.',
      'Ich bin noch bei der Ausführung und halte die Richtung gerade sauber zusammen.',
      'Ich bleibe noch kurz dran, bis die Sache rund aussieht.',
      'Ich gehe noch tiefer in die Details, damit später nichts stolpert.',
      'Ich halte die aktuelle Stelle noch unter Feinschliff.',
      'Ich arbeite den Schritt noch so aus, dass er nicht wackelt.',
      'Ich bin noch in der Detailrunde, bis die Kante ruhig ist.',
      'Ich ziehe den aktuellen Schritt noch auf belastbar.',
      'Ich halte noch kurz die Architektur über die laufende Stelle.',
    ],
  },
}

export function fillToolPhrase(template: string, vars: { target: string; place: string }): string {
  return template
    .replaceAll('{target}', vars.target)
    .replaceAll('{place}', vars.place)
}
